export { useMagneticEffect } from './useMagneticEffect'
export type { MagneticEffectOptions } from './useMagneticEffect'
export { useParallax } from './useParallax'
export type { ParallaxResult } from './useParallax'
export { useScrollAnimation } from './useScrollAnimation'
